name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.run_number }}
            ${{ secrets.DOCKER_USERNAME }}/hello-app:latest

      - name: Checkout Manifests Repository
        uses: actions/checkout@v4
        with:
          repository: Elleres/hello-manifests 
          token: ${{ secrets.MANIFEST_REPO_PAT }}
          path: hello-manifests

      - name: Update image tag in manifest
        run: |
          sed -i "s|image: gelleres/hello-app:.*|image: gelleres/hello-app:${{ github.run_number }}|" hello-manifests/manifests/deploy.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MANIFEST_REPO_PAT }}
          commit-message: 'feat: Atualiza a imagem para a versão ${{ github.run_number }}'
          title: 'Atualiza a imagem hello-app para a versão ${{ github.run_number }}'
          body: 'Este PR atualiza a tag da imagem `hello-app` para a versão mais recente do build do CI/CD.'
          branch: 'update-hello-app-image-${{ github.run_number }}'
          base: 'main'
          delete-branch: true
          enable-automerge: true
          automerge-method: true
